### ISSUE TITLE
Compilation Failure в новом проекте

### ISSUE THREAD

**Issue by Lopll** [NauEngine/NauEditorPublic#1]
Здравствуйте, я установил движок, создал новый проект и сразу же увидел это сообщение, но не знаю, влияет ли оно на работу движка...

![{871BBA61-66A6-4283-98A0-F7F682411273}](https://github.com/user-attachments/assets/eac5f7fc-edcf-4556-98b3-075734ed5253)

Также в консоли есть много сообщений:

![{2C38C920-BF92-4FA4-ABFF-3EEA7129A64B}](https://github.com/user-attachments/assets/96d4a4e9-0b53-40bf-b444-f3bc4aa1d826)
![{DC1941D2-B00D-4B88-8F35-4D7054418092}](https://github.com/user-attachments/assets/b25043f2-b941-4afc-a464-a1607da460cb)

Содержание log_compile.txt:

Log started: 26.11.2024 13:46:06
Staring E:/Programs/NauEditor/BuildToolCmd.exe compile --project E:/1/Creativity/Projects/Nau/Aboba --preset win_vs2022_x64_dll --config=Release
CreateProcess with args cmake -BE:/1/Creativity/Projects/Nau/Aboba/build -SE:/1/Creativity/Projects/Nau/Aboba --preset win_vs2022_x64_dll -DCMAKE_INSTALL_PREFIX=E:/1/Creativity/Projects/Nau/Aboba/bin -DNAU_CORE_TOOLS=OFF -DNAU_PACKAGE_BUILD=ON -DNAU_CORE_TESTS=OFF -DNAU_CORE_SAMPLES=OFF -DNAU_FORCE_ENABLE_SHADER_COMPILER_TOOL=ON failed. Error 2
Build failed: Could not generate solution file!
Log stopped: 26.11.2024 13:46:06

Движок устанавливал через .exe установщик.
ОС: windows 11 (64)
Версия движка: 0.10.0 beta

**Comment by den-bel** [comment]
помогло вот это https://github.com/NauEngine/NauEnginePublic?tab=readme-ov-file#vcpkg-seup

**Comment by Unbihexium** [comment]
```
>"C:/Program Files/NauEngine/NauEditor/BuildToolCmd.exe" --verbose compile --project C:/Nau/zombine --preset win_vs2022_x64_dll --config=Release
Compile project at path C:/Nau/zombine
Preset CMake variables:

  BUILD_SHARED_LIBS:BOOL="TRUE"
  CMAKE_CONFIGURATION_TYPES="Debug;Release"
  CMAKE_EXPORT_COMPILE_COMMANDS:BOOL="TRUE"
  CMAKE_SYSTEM_VERSION="10.0"
  CMAKE_TOOLCHAIN_FILE="/scripts/buildsystems/vcpkg.cmake"
  EASTL_BUILD_BENCHMARK:BOOL="FALSE"
  EASTL_BUILD_TESTS:BOOL="FALSE"
  NAU_BUILD_SDK:BOOL="TRUE"

CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:152 (message):
  Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
Build failed: Could not generate solution file!
Could not generate solution file!
```
Проблема вероятно здесь, не правильно резолвится путь   CMAKE_TOOLCHAIN_FILE="/scripts/buildsystems/vcpkg.cmake"
Должно быть с VCPKG_ROOT, но она не задана.

**Comment by AnatolyRyzhakov** [comment]
Добрый день!

Это сообщение говорит о том, что не удалось собрать MainGameModule.dll отвечающий за игровую логику (скрипты) в проекте

Чтобы избежать этой ошибки, необходимо:
- Установить Python (не ниже 3.10)
- Установить CMake
- Подготовить к работе vcpkg (склонировать репозиторий, выполнить bootstrap.bat, прописать VCPKG_ROOT в переменные окружения)
- Установить средства сборки C++ кода (Visual Studio с добавленным Workload: "Desktop development with C++" )

Если всё сделано правильно, то при последующей загрузке проекта нужный код будет скомпилирован

К сожалению, данные 3rd party не входят в состав инсталляционного пакета и нужно их доустанавливать самостоятельно.
Информация об этом есть в самом инсталляторе (в блоке с лицензией), а так же в нашем мануале, в разделе [Сборка движка из исходников](https://nauengine.org/docs/beta/user-doc/introduction_to_nau/install_nau/install_nau_doc.html#id4)

Документация так же ожидает правок в ближайшее время

Спасибо большое за Ваш репорт, приносим извинения за неудобства!

**Comment by Lopll** [comment]
Спасибо, установка Python, Cmake и vcpkg помогли
