### ISSUE TITLE
Плоховатая адаптация под разные экраны

### ISSUE THREAD

**Issue by ArtyomBina** [NauEngine/NauEditorPublic#19]
У меня тупо не влазиет движок в экран, верхняя панель не влазиет из за этого вся работа с движком идёт на нет

**Comment by Proker57** [comment]
Не плохо было бы указать разрешение экрана

**Comment by ArtyomBina** [comment]
> Не плохо было бы указать разрешение экрана и масштаб ui в системе

1920x1080, но у меня ещё стоит hyprland (Arch Linux )и окна открываются не на весь экран

**Comment by Blockerbug** [comment]
Про Linux сборку уже есть issue #3 
Пока честной Linux сборки нет, бессмысленно репортить подобные баги))

**Comment by nikolayli** [comment]
@ArtyomBina, секундочку, я правильно понимаю что вы собрали на Linux движок, который поддерживает пока только DirectX. Можно спросить как вы это сделали и можете ли вы поделиться своими исходниками?
