### ISSUE TITLE
Compilation Failure в новом проекте 

### ISSUE THREAD

**Issue by Hann1bal** [NauEngine/NauEditorPublic#26]
Ошибка сборки нового проекта:
```
Log started: 03.12.2024 21:53:11
Staring C:/Program Files/NauEngine/NauEditor/BuildToolCmd.exe compile --project H:/testss/Test --preset win_vs2022_x64_dll --config=Release
Build failed: Could not generate solution file!
Log stopped: 03.12.2024 21:53:12
```
При этом если я вручную стартую сборку:
![image](https://github.com/user-attachments/assets/5e41fe77-cd9f-40f6-aea5-509b3f074777)
Проект почему то ищет Cmake_Root хотя я всё прописал
Все зависимости установлены.

**Comment by Hann1bal** [comment]
А ну и вопрос а можно выводить эту информацию в самом редакторе?
![image](https://github.com/user-attachments/assets/6a59283a-aa34-414f-b859-1da66f3b9e3b)
Например тут?

**Comment by Hann1bal** [comment]
UPD:
Прописал переменную среды, перепроверил, что vcpkg установил,vcpkg  батник запустил, попробовал перекомпилить получил ошибку такую:
![image](https://github.com/user-attachments/assets/e68f9587-d989-4e00-be01-820e8e9ae730)

**Comment by Blockerbug** [comment]
Вот этот путь стоит привести к виндовому виду
`CMAKE_TOOLCHAIN_FILE="/scripts/buildsystems/vcpkg-cmake" `
То есть `C:\\` и так далее

**Comment by bNick** [comment]
Тут скорее всего не выставленны нужные переменные окружения из VisualStudio в системе хотя они должны были прописаться при установке студии. Как вариант попробуйте запустить команду из Developer Comand Prompt... (Можно найти через поиск в меню "Пуск") там точно все что нужно уже прописано

**Comment by Hann1bal** [comment]
Проблема решена. Вопрос остался только как, я в VS22 закинул еще разработку игр на с++ плюсом докинул туда новейшую SDK для 11 windows. Теперь всё работает. Возможно нужно ставить не 10 SDK, а SDK под целевую систему.
![image](https://github.com/user-attachments/assets/f3ea65e9-1920-44a1-a4d0-28b29329dc17)
