### ISSUE TITLE
Не работает компонент Camera

### ISSUE THREAD

**Issue by Proker57** [NauEngine/NauEditorPublic#9]
Если добавить камеру на сцену и запустить playmode, view point идёт через Scene Camera, но по позиции 0.0.0
В консоли сообщения что поля скрипта камеры не могут быть получены

**Comment by Mramidhub** [comment]
На это обратите внимание, пожалуйста, в числе первых правок.
Без камеры что-то тестить бесполезно практически.

**Comment by AnatolyRyzhakov** [comment]
Добрый день!

Внимание обратили. Спасибо за репорт.

Будем править в ближайшем хот-фиксе

**Comment by Mramidhub** [comment]
> Если добавить камеру на сцену и запустить playmode, view point идёт через Scene Camera, но по позиции 0.0.0 В консоли сообщения что поля скрипта камеры не могут быть получены

У тебя заработелао? По мне так вроде проблема еще сохраняется.
